---
title: "Analysis 2.12"
author: "Lauren Kaapcke"
date: "February 12, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

# Packages
library(tidyverse)
library(knitr)
library(readr)
#install.packages("stargazer")
library(stargazer)
#install.packages("janitor")
library(janitor)
library(MASS)
#install.packages(robust)
#library(robust)
library(car)

```

```{r}

# Import and tidy data
data <- read_csv("regression_10km.csv")

# Reclassify columns
data$Pool <- as.factor(data$Pool)
data$Bar <- as.factor(data$Bar)
data$Biz_Center <- as.factor(data$Biz_Center)
data$Conference <- as.factor(data$Conference)
data$Mtg_Rooms <- as.factor(data$Mtg_Rooms)
data$Wheelchair <- as.factor(data$Wheelchair)
data$Concierge <- as.factor(data$Concierge)
data$Laundry <- as.factor(data$Laundry)
data$Gym <- as.factor(data$Gym)
data$Wifi <- as.factor(data$Wifi)
data$Multilingual <- as.factor(data$Multilingual)
data$No_Smoke <- as.factor(data$No_Smoke)
data$Breakfast_ <- as.factor(data$Breakfast_)
data$Air_Trans <- as.factor(data$Air_Trans)
data$Free_Parking <- as.factor(data$Free_Parking)
data$Beachfront <- as.factor(data$Beachfront)
data$City <- as.factor(data$City)
data$city_comp <- as.factor(data$city_comp)
data$dive_site <- as.factor(data$dive_site)
data$`3_star` <- as.factor(data$`3_star`)
data$`4_star` <- as.factor(data$`4_star`)
data$`5_star` <- as.factor(data$`5_star`)
data$near <- as.factor(data$near)
data$mid <- as.factor(data$mid)
data$far <- as.factor(data$far)
data$position <- as.factor(data$position)
data$zip <- as.factor(data$zip)

# Add a column with average price, select only wanted columns
data1 <- data %>%
  dplyr::select(2, 6:50, -LATITUDE, -LONGITUDE, -NEAR_DIST_SHORE) %>% 
  mutate(avg_price = (Low_Price + High_Price)/2) %>% 
  clean_names()
# Correct the rooms column to reviews
names(data1)[3] <- "num_reviews"
# n = 428 for data1

# Filter out hotels that are missing class and review data
data2 <- data1 %>% 
  filter(class != "#N/A" | number_rooms != "#N/A")
data2$class <- as.numeric(data2$class)
data2$number_rooms <- as.numeric(data2$number_rooms)
# n = 385 for data2

```

```{r}

# Summarize the data:
stats1 <- data1 %>% 
  group_by(city) %>% 
  summarize(
    mean_price = mean(avg_price),
    mean_coral = mean(coral_cover),
    low_price = mean(low_price, sort = desc),
    count = length(city)
  )
stats1

stats2 <- data4 %>% 
  group_by(city) %>% 
  summarize(
    mean_price = mean(avg_price),
    mean_coral = mean(coral_cover),
    mean_rooms = mean(number_rooms),
    count = length(city),
    mean_beach = mean(beach_width)
  )
stats2

overall_stats1 <- data4 %>% 
  summarize(
     mean_price = mean(avg_price),
    mean_coral1 = mean(coral_cover)*0.01,
    low_price = mean(low_price, sort = desc),
    beach = mean(beach_width),
    mean_rooms = mean(number_rooms)
  )
overall_stats1

# Decision to remove Boca and Delray from both data sets (sample sizes too small)
data3 <- data1 %>% 
  filter(city != "Boca" & city != "Delray")
# n = 414 for data3

data4 <- data2 %>% 
  filter(city!= "Boca" & city != "Delray")
# n = 372 for data4

```

```{r}

# Focus on a beach width regression for data3, and then try data4
# Way to transform vars: log(beach_width + sqrt(1 + beach_width^2))

plot_width <- ggplot(data = data3, aes(x = beach_width, y = avg_price)) +
  geom_point() +
  facet_wrap(~city, scales = "free")
plot_width

hist_width <- ggplot(data = data3, aes(x = beach_width)) +
  geom_histogram() +
  facet_wrap(~city_comp, scales = "free")
hist_width

width2 <- lm(log(avg_price) ~ log(beach_width + sqrt(1 + beach_width^2)) + log(near_dist_beach) + log(rating) + log(dist_to_access_points) +  city, data = data3)
summary(width2)

width1 <- lm(log(avg_price) ~ log(beach_width + sqrt(1 + beach_width^2)) + log(near_dist_beach) + log(rating) + log(dist_to_access_points) +  city + pool + breakfast + beachfront + gym + free_parking + air_trans + log(dist_to_airport) + concierge + conference, data = data3)
summary(width1)
plot(width1)

# Use a few versions of the regression below for the preso
width3 <- lm(log(avg_price) ~ log(beach_width + sqrt(1 + beach_width^2)) + log(near_dist_beach) + log(rating) + log(dist_to_access_points) +  city + log(class) + pool + breakfast + beachfront + gym + free_parking + air_trans + log(dist_to_airport) + concierge + conference + city, data = data4)
summary(width3)
plot(width3)

width_all <- lm(log(avg_price) ~ log(beach_width + sqrt(1 + beach_width^2)) + log(rating) + log(num_reviews) + pool + bar + biz_center + conference + mtg_rooms + wheelchair + concierge + laundry + gym + wifi + multilingual + no_smoke + breakfast + air_trans + free_parking + beachfront + log(near_dist_beach) + log(dist_to_access_points) + log(dist_to_airport) + log(dist_to_reef), data = data2)
summary(width_all)

width_step <- stepAIC(width_all, direction = "both")
width_step$anova
# Suggested model: log(avg_price) ~ log(beach_width + sqrt(1 + beach_width^2)) + log(rating) + log(num_reviews) + mtg_rooms + concierge + gym + breakfast + air_trans + free_parking + beachfront + log(dist_to_access_points) + log(dist_to_airport)

beach <- lm(log(beach_width + sqrt(1 + beach_width^2)) ~ log(coral_cover) + log(dist_to_reef) + city, data = data4)
summary(beach)

```

```{r}
# Do some coral regressions

plot_coral <- ggplot(data = data3, aes(x = coral_cover, y = avg_price)) +
  geom_point() +
  facet_wrap(~city_comp, scales = "free")
plot_coral

hist_coral <- ggplot(data = data3, aes(x = coral_cover)) +
  geom_histogram() +
  facet_wrap(~city_comp, scales = "free")
hist_coral

coral1 <- lm(log(avg_price) ~ log(coral_cover) + log(dist_to_reef) + city + log(rating) + log(class) + log(number_rooms) + conference + concierge + air_trans + beachfront + log(num_dive + sqrt(1 + num_dive^2)), data = data4)
summary(coral1)

coral_all <- lm(log(avg_price) ~ log(coral_cover) + log(rating) + log(num_reviews) + pool + bar + biz_center + conference + mtg_rooms + wheelchair + concierge + laundry + gym + wifi + multilingual + no_smoke + breakfast + air_trans + free_parking + beachfront + log(near_dist_beach) + log(dist_to_access_points) + log(dist_to_airport) + log(dist_to_reef) + log(num_dive + sqrt(1 + num_dive^2)) + dive_site + x3_star + x4_star + x5_star + log(class) + log(number_rooms) + near + mid + far + position , data = data4)
summary(coral_all)
coral_step <- stepAIC(coral_all, direction = "both")
coral_step$anova

# Recommended model: log(avg_price) ~ log(rating) + log(num_reviews) + biz_center + conference + concierge + beachfront + log(near_dist_beach) + log(dist_to_airport) + x3_star + x5_star + log(class) + log(number_rooms) +  near + mid

test <- lm(log(avg_price) ~ log(coral_cover) + log(rating) + log(num_reviews) + biz_center + conference + concierge + beachfront + log(near_dist_beach) + log(dist_to_airport) + x3_star + x4_star + x5_star + log(number_rooms) + near + mid, data = data4)
summary(test)

# Use the regression below for coral cover in the presentation
test1 <- lm(log(avg_price) ~ log(coral_cover) + log(dist_to_reef) + log(rating) + log(near_dist_beach) + log(dist_to_access_points) + pool + gym + free_parking + conference + air_trans + position + beachfront + breakfast + log(class) + log(dist_to_airport) + city, data = data4)
summary(test1)

# width3 <- lm(log(avg_price) ~ log(beach_width + sqrt(1 + beach_width^2)) + log(near_dist_beach) + log(rating) + log(dist_to_access_points) +  city + log(class) + pool + breakfast + beachfront + gym + free_parking + air_trans + log(dist_to_airport) + concierge + conference, data = data4)
```

```{r}

# Models and stargazer table for presentation:

coral_final <- lm(log(avg_price) ~ log(coral_cover) + log(dist_to_reef) + log(rating) + log(class) + air_trans + beachfront + breakfast + conference + free_parking + gym + pool + log(dist_to_access_points) + log(near_dist_beach) + position, data = data4)
summary(coral_final)

coral_1 <- lm(log(avg_price) ~ log(coral_cover) + log(dist_to_reef) + log(rating) + log(class), data = data4)
summary(coral_1)      

coral_reg <- stargazer(coral_1, coral_final, type = "html", report = "vc*", model.numbers = F, 
                         title = "Ecotourism Log-Log Regression Results",
                         dep.var.labels=c("Standard Hotel Room Price"),
                         column.labels = c("Simple Model", "Chosen Model"),
                         covariate.labels = c("Coral Cover", "Distance to Reef", "Guest Rating", "Hotel Class", "Airport Transport", "Beachfront", "Breakfast Included", "Conference Center", "Free Parking", "Gym", "Pool", "Distance to Beach Access", "Distance to Beach", "City Block 1", "City Block 2"),
                         out = "coral_reg.html")
                    
                    


```

```{r}

test <- lm(log(beach_width + sqrt(1 + beach_width^2)) ~ log(coral_cover) + log(dist_to_reef) + city, data = data4)
summary(test)

```

```{r}

#Try putting beach width and coral cover together in linear model
reg_all <- lm(avg_price ~ coral_cover + beach_width + rating + num_reviews + pool + bar + biz_center + conference + mtg_rooms + wheelchair + concierge + laundry + gym + wifi + multilingual + no_smoke + breakfast + air_trans + free_parking + beachfront + near_dist_beach + dist_to_access_points + dist_to_airport + dist_to_dive + dist_to_reef + num_dive + city + city_comp + dive_site + class + number_rooms + x3_star + x4_star + x5_star + near + mid + far + position, data = data4)
summary(reg_all)

all_reg_step <- stepAIC(reg_all, direction = "both")
all_reg_step$anova

# Recommended model from stepwise regression: avg_price ~ rating + pool + bar + conference + air_trans + beachfront + num_dive + city_comp + class + x3_star + x5_star + far

all_1 <- lm(avg_price ~ coral_cover + beach_width + rating + pool + bar + conference + air_trans + beachfront + num_dive + class + far, data = data4)
summary(all_1)
# Coral is negative, but not significant. Beach width is positive and significant.

all_2 <- lm(avg_price ~ coral_cover + beach_width + rating + class, data = data4)
summary(all_2)
# Coral is positive and significant, beach width is positive but not significant

all_log_linear <- lm(log(avg_price) ~ coral_cover + beach_width + rating + class, data = data4)
summary(all_log_linear)
# Coral and beach width are both positive, coral is significant. Adjusted R^2 is higher than the log-log model with the same variables

all_log_2 <- lm(log(avg_price) ~ log(coral_cover) + log(beach_width + sqrt(1 + beach_width^2)) + log(rating) + log(class), data = data4)
summary(all_log_2)
# Coral cover is significant and positive, beach width is negative and not significant. 

log_ln_city <- lm(log(avg_price) ~ coral_cover + beach_width + rating + class + city, data = data4)
summary(log_ln_city)

data_mb <- data4 %>% 
  filter(city == "MiamiBeach")

data_kw <- data4 %>% 
  filter(city == "KeyWest")

data_fl <- data4 %>% 
  filter(city == "FtLauderdale")

log_ln_kw <- lm(log(avg_price) ~ coral_cover + beach_width + rating + class, data = data_kw)
summary(log_ln_kw)
# coral negative, beach width positive, neither significant

log_ln_fl <- lm(log(avg_price) ~ coral_cover + beach_width + rating + class, data = data_fl)
summary(log_ln_fl)
# coral and beach width positive, neither significant

log_ln_mb <- lm(log(avg_price) ~ coral_cover + beach_width + rating + class, data = data_mb)
summary(log_ln_mb)
# coral negative and not significant, beach width positive and significant

```

```{r}
# try  with high and low price

# LOW
all_low <- lm(low_price ~ coral_cover + beach_width + rating + pool + bar + conference + air_trans + beachfront + num_dive + class + far, data = data4)
summary(all_low)
# beach width and coral cover both positive, neither significant

all_low_log_linear <- lm(log(low_price) ~ coral_cover + beach_width + rating + class, data = data4)
summary(all_low_log_linear)
# coral cover positive and significant; beach width negative and significant

all_low_log <- lm(log(low_price) ~ log(coral_cover) + log(beach_width + sqrt(1 + beach_width^2)) + log(rating) + log(class), data = data4)
summary(all_low_log)
# coral cover positive and significant, beach width negative and significant

# HIGH
all_high <- lm(high_price ~ coral_cover + beach_width + rating + pool + bar + conference + air_trans + beachfront + num_dive + class + far, data = data4)
summary(all_high)
# coral cover negative but not significant; beach width positive and significant

all_high_log <- lm(log(high_price) ~ log(coral_cover) + log(beach_width + sqrt(1 + beach_width^2)) + log(rating) + log(class), data = data4)
summary(all_high_log)
#coral cover positive and significant, beach width positive but not significant

all_high_log_linear <- lm(log(high_price) ~ coral_cover + beach_width + rating + class, data = data4)
summary(all_high_log_linear)
# BOTH coral cover and beach width are positive and significant!!! Adjusted R-squared = 0.51

# add in more variables with high log-linear
all_high_log_linear2 <- lm(log(high_price) ~ coral_cover + beach_width + rating + class + number_rooms, data = data4)
summary(all_high_log_linear2)
# added number_rooms. still both positive and significant

all_high_log_linear3 <- lm(log(high_price) ~ coral_cover + beach_width + rating + class + number_rooms + position, data = data4)
summary(all_high_log_linear3)
# added position. still both positive and significant

all_high_log_linear4 <- lm(log(high_price) ~ coral_cover + beach_width + rating + class + number_rooms + position + pool, data = data4)
summary(all_high_log_linear4)
# added pool. still both positive and significant

all_high_log_linear5 <- lm(log(high_price) ~ coral_cover + beach_width + rating + class + number_rooms + position + pool + gym, data = data4)
summary(all_high_log_linear5)
# added gym

all_high_log_linear6 <- lm(log(high_price) ~ coral_cover + beach_width + rating + class + number_rooms + position + pool + gym + free_parking, data = data4)
summary(all_high_log_linear6)
# added free parking

all_high_log_linear7 <- lm(log(high_price) ~ coral_cover + beach_width + rating + class + number_rooms + position + pool + gym + free_parking + concierge, data = data4)
summary(all_high_log_linear7)
# added concierge

all_high_log_linear8 <- lm(log(high_price) ~ coral_cover + beach_width + rating + class + number_rooms + position + pool + gym + free_parking + concierge + conference, data = data4)
summary(all_high_log_linear8)
# added conference

all_high_log_linear9 <- lm(log(high_price) ~ coral_cover + beach_width + rating + class + number_rooms + position + pool + gym + free_parking + concierge + conference + biz_center, data = data4)
summary(all_high_log_linear9)
# added biz center; adj. R^2 = 0.5242

all_high_log_linear10 <- lm(log(high_price) ~ coral_cover + beach_width + rating + class + number_rooms + position + pool + gym + free_parking + concierge + conference + biz_center + air_trans, data = data4)
summary(all_high_log_linear10)
# added air trans; adj. R^2 = 0.5259

all_high_log_linear11 <- lm(log(high_price) ~ coral_cover + beach_width + rating + class + number_rooms + position + pool + gym + free_parking + concierge + conference + biz_center + air_trans + beachfront, data = data4)
summary(all_high_log_linear11)
# added beachfront; adj. R^2 = 0.5292

all_high_log_linear12 <- lm(log(high_price) ~ coral_cover + beach_width + rating + class + number_rooms + position + pool + gym + free_parking + concierge + conference + biz_center + air_trans + beachfront + breakfast, data = data4)
summary(all_high_log_linear12)
# added breakfast; adj. R^2 = 0.5279

all_high_log_linear13 <- lm(log(high_price) ~ coral_cover + beach_width + rating + class + number_rooms + position + pool + bar + gym + free_parking + concierge + conference + biz_center + air_trans + beachfront + breakfast, data = data4)
summary(all_high_log_linear13)
# added bar. Both positive and significant, Adj. R^2 = 0.5282

```


```{r}

# More high log-linear variables

all_high_log_linear_more <- lm(log(high_price) ~ coral_cover + beach_width + rating + class + number_rooms + position + pool + bar + gym + free_parking + concierge + conference + biz_center + air_trans + beachfront + breakfast + num_dive, data = data4)
summary(all_high_log_linear_more)
# adding number of dive spots makes coral cover not significant (but positive). Beach width is positive and significant. R^2 = 0.559

all_high_log_linear_more2 <- lm(log(high_price) ~ coral_cover + beach_width + rating + class + number_rooms + position + pool + bar + gym + free_parking + concierge + conference + biz_center + air_trans + beachfront + breakfast + dist_to_reef, data = data4)
summary(all_high_log_linear_more2)
# added distance to reef. both positive and significant! R^2 = 0.529

all_high_log_linear_more3 <- lm(log(high_price) ~ coral_cover + beach_width + rating + class + number_rooms + position + pool + bar + gym + free_parking + concierge + conference + biz_center + air_trans + beachfront + breakfast + dist_to_reef + dist_to_dive, data = data4)
summary(all_high_log_linear_more3)
# adding dist to dive makes coral cover negative and not significant. R^2 = 0.5633

all_high_log_linear_more4 <- lm(log(high_price) ~ coral_cover + beach_width + rating + class + number_rooms + position + pool + bar + gym + free_parking + concierge + conference + biz_center + air_trans + beachfront + breakfast + dist_to_reef + dist_to_airport, data = data4)
summary(all_high_log_linear_more4)
# adding dist to airport makes coral negative and not significant. R^2 = 0.5668

all_high_log_linear_more5 <- lm(log(high_price) ~ coral_cover + beach_width + rating + class + number_rooms + position + pool + bar + gym + free_parking + concierge + conference + biz_center + air_trans + beachfront + breakfast + dist_to_reef + dist_to_access_points, data = data4)
summary(all_high_log_linear_more5)
# both positive and significant after adding dist to access points. R^2 = 0.5326

all_high_log_linear_more6 <- lm(log(high_price) ~ coral_cover + beach_width + rating + class + number_rooms + position + pool + bar + gym + free_parking + concierge + conference + biz_center + air_trans + beachfront + breakfast + dist_to_reef + wheelchair + dist_to_access_points, data = data4)
summary(all_high_log_linear_more6)
# added wheelchair

all_high_log_linear_more7 <- lm(log(high_price) ~ coral_cover + beach_width + rating + class + number_rooms + position + pool + bar + gym + free_parking + concierge + conference + biz_center + air_trans + beachfront + breakfast + dist_to_reef + wheelchair + laundry + dist_to_access_points, data = data4)
summary(all_high_log_linear_more7)
# added laundry

all_high_log_linear_more8 <- lm(log(high_price) ~ coral_cover + beach_width + rating + class + number_rooms + position + pool + bar + gym + free_parking + concierge + conference + biz_center + air_trans + beachfront + breakfast + dist_to_reef + wheelchair + laundry + no_smoke + dist_to_access_points, data = data4)
summary(all_high_log_linear_more8)
# added no smoke

all_high_log_linear_more9 <- lm(log(high_price) ~ coral_cover + beach_width + rating + class + number_rooms + position + pool + bar + gym + free_parking + concierge + conference + biz_center + air_trans + beachfront + breakfast + dist_to_reef + wheelchair + laundry + no_smoke + mtg_rooms + dist_to_access_points, data = data4)
summary(all_high_log_linear_more9)

all_high_log_linear_more_city <- lm(log(high_price) ~ coral_cover + beach_width + rating + class + number_rooms + position + pool + bar + gym + free_parking + concierge + conference + biz_center + air_trans + beachfront + breakfast + dist_to_reef + wheelchair + laundry + no_smoke + mtg_rooms + dist_to_access_points + city, data = data4)
summary(all_high_log_linear_more_city)
# added meeting rooms

results <- stargazer(all_high_log_linear_more9, all_high_log_linear_more_city, type = "html", report = "vc*", model.numbers = F, title = "Log-Linear Regression Results",
                         dep.var.labels=c("Standard Hotel Room Price"),
                         column.labels = c("Without City", "With City"),
                         covariate.labels = c("Coral Cover", "Beach Width", "Rating", "Class", "Number of Rooms", "Position Mid","Position Near", "Pool", "Bar", "Gym","Free Parking","Concierge","Conference","Business Center","Air Transport","Beachfront","Breakfast","Distance to Reef", "Wheelchair", "Laundry", "Non Smoking", "Meeting Rooms","Distance to Access", "Key West", "Miami Beach"),
                         out = "model_reg.html")

```

```{r}

# Running regressions on zip code instead of city

stats_zip <- data4 %>% 
  group_by(zip) %>% 
  summarize(
    mean_price = mean(avg_price),
    mean_coral = mean(coral_cover),
    low_price = mean(low_price, sort = desc),
    mean_rooms = mean(number_rooms),
    count = length(zip),
    mean_beach = mean(beach_width)
  )
stats_zip

# Try running log-linear with zip
all_high_log_linear_zip <- lm(log(high_price) ~ coral_cover + beach_width + rating + class + number_rooms + position + pool + bar + gym + free_parking + concierge + conference + biz_center + air_trans + beachfront + breakfast + dist_to_reef + wheelchair + laundry + no_smoke + mtg_rooms + dist_to_access_points + zip, data = data4)
summary(all_high_log_linear_zip)
# Reference zip is 33040 Coral cover is still negative overall, let's separate to find which zips have negative relationship with coral cover:

data_33040 <- data4 %>%
  filter(zip == "33040")

data_33139 <- data4 %>%
  filter(zip == "33139")

data_33140 <- data4 %>%
  filter(zip == "33140")

data_33141 <- data4 %>% 
  filter(zip == "33141")

data_33304 <- data4 %>%
  filter(zip == "33304")

data_33305 <- data4 %>%
  filter(zip == "33305")

data_33308 <- data4 %>% 
  filter(zip == "33308")

data_33316 <- data4 %>% 
  filter(zip == "33316")

# Re-run regression on each zip:
high_lgln_33040 <- lm(log(high_price) ~ coral_cover + beach_width + rating + class + number_rooms + position + pool + bar + gym + free_parking + concierge + conference + biz_center + air_trans + beachfront + breakfast + dist_to_reef + wheelchair + laundry + no_smoke + mtg_rooms + dist_to_access_points, data = data_33040)
summary(high_lgln_33040)
# Coral is negative, not significant

high_lgln_33139 <- lm(log(high_price) ~ coral_cover + beach_width + rating + class + number_rooms + position + pool + bar + gym + free_parking + concierge + conference + biz_center + air_trans + beachfront + breakfast + dist_to_reef + wheelchair + laundry + no_smoke + mtg_rooms + dist_to_access_points, data = data_33139)
summary(high_lgln_33139)
# Coral is negative, not significant

high_lgln_33140 <- lm(log(high_price) ~ coral_cover + beach_width + rating + class + number_rooms + position + pool + bar + gym + free_parking + concierge + conference + biz_center + air_trans + beachfront + breakfast + dist_to_reef + wheelchair + laundry + no_smoke + mtg_rooms + dist_to_access_points, data = data_33140)
summary(high_lgln_33140)
# Coral is positive, not significant

high_lgln_33141 <- lm(log(high_price) ~ coral_cover + beach_width + rating + class + number_rooms + position + pool + bar + gym + free_parking + concierge + conference + biz_center + air_trans + beachfront + breakfast + dist_to_reef + wheelchair + laundry + no_smoke + mtg_rooms + dist_to_access_points, data = data_33141)
summary(high_lgln_33141)
# Coral is negative, not significant

high_lgln_33304 <- lm(log(high_price) ~ coral_cover + beach_width + rating + class + number_rooms + position + pool + bar + gym + free_parking + concierge + conference + biz_center + air_trans + beachfront + breakfast + dist_to_reef + wheelchair + laundry + no_smoke + mtg_rooms + dist_to_access_points, data = data_33304)
summary(high_lgln_33304)
# Coral cover is positive, not significant

high_lgln_33308 <- lm(log(high_price) ~ coral_cover + beach_width + rating + class + number_rooms + position + bar + gym + free_parking + concierge + conference + biz_center + air_trans + beachfront + breakfast + dist_to_reef + wheelchair + laundry + no_smoke + mtg_rooms + dist_to_access_points, data = data_33308)
summary(high_lgln_33308)
# Coral cover is negative and not significant
# Had to remove pool because n = 11 and all hotels had pools

# Did not run regressions for 33305 or 33316 because n = 3 and n = 7 respectively.
# Coral has a positive impact in 33304 (Ft. Lauderdale) and 33140 (Miami Beach). Coral has a negative impact in 33040 (Key west), 33308 (Ft. Lauderdale, however n = 11), 333139 (South Beach), 33141 (Miami Beach).


```

```{r}
# Try running regressions including crime data as a numeric variable

lgln_crime <- lm(log(high_price) ~ coral_cover + beach_width + rating + class + number_rooms + position + bar + gym + free_parking + concierge + conference + biz_center + air_trans + beachfront + breakfast + dist_to_reef + wheelchair + laundry + no_smoke + mtg_rooms + dist_to_access_points + crime, data = data4)
summary(lgln_crime)

avg_lgln_crime <- lm(log(avg_price) ~ coral_cover + beach_width + rating + class + number_rooms + position + bar + gym + free_parking + concierge + conference + biz_center + air_trans + beachfront + breakfast + dist_to_reef + wheelchair + laundry + no_smoke + mtg_rooms + dist_to_access_points + crime, data = data4)
summary(avg_lgln_crime)
# Both beach width and coral cover are positive and significant. 

avg_lgln_crime_city <- lm(log(avg_price) ~ coral_cover + beach_width + rating + class + number_rooms + position + bar + gym + free_parking + concierge + conference + biz_center + air_trans + beachfront + breakfast + dist_to_reef + wheelchair + laundry + no_smoke + mtg_rooms + dist_to_access_points + crime + city, data = data4)
summary(avg_lgln_crime_city)
# Coral is negative and not significant, beach width is positive and significant.

#Check if crime is correlated with anything
data_cont <- data4 %>%
  dplyr::select(2:3, 22:29, 33:34, 43:44)

plot(data_cont)
cor(data_cont)
# Crime is negatively correlated with beach width. Places with higher crime are expected to have narrower beaches. Not a high correlation -0.38.

avg_lgln_crime_int <- lm(log(avg_price) ~ coral_cover + beach_width + rating + class + number_rooms + position + bar + gym + free_parking + concierge + conference + biz_center + air_trans + beachfront + breakfast + dist_to_reef + wheelchair + laundry + no_smoke + mtg_rooms + dist_to_access_points + crime + city + coral_cover*city, data = data4)
summary(avg_lgln_crime_int)
# Coral alone is positive, but not significant. Coral interaction terms with Key West and MB are negative, but not significant. Interpretation: a person's WTP for a hotel depends on the amount of coral cover AND the city. This is lower in MB & KW. A person's willingess to pay for a hotel with more coral depends on what city it is in. 

```

```{r}

# Try running some robust linear models, perhaps this will smooth the effects of outliers, etc. in the data.

# First compare linear and log linear models & residuals to ensure log linear is the better fit

linear <- lm(avg_price ~ coral_cover + beach_width + rating + class + zip, data = data4)
summary(linear)

lgln <- lm(log(avg_price) ~ coral_cover + beach_width + rating + class + zip, data = data4)
summary(lgln)

lglg <- lm(log(avg_price) ~ log(coral_cover) + log(beach_width + sqrt(1 + beach_width^2)) + log(rating) + log(class) + zip, data = data4)
summary(lglg)

# Now compare residuals
par(mfrow = c(2,2))
plot(linear)

par(mfrow = c(2,2))
plot(lgln)

par(mfrow = c(2,2))
plot(lglg)

# Look at problematic observations 101, 102, 104, 105, 170, 294, 297, 357

data4[c(101, 102, 104, 105, 170, 294, 297, 357), 1:44]

# 5 of these hotels are in South Beach, 2 in Miami Beach and 1 in Fort Lauderdale. 6 of them have average prices above $1000 and 8 of them have average prices far above the entire sample. The question is: do these observations have a lot of leverage to alter regression results?

# Look at observations with large Cook's Distances:

cooks <- cooks.distance(linear)
r <- stdres(linear)
a <- cbind(data4, cooks, r)
a[cooks > 4/372, ]
# 14 observations have a larger than expected Cook's distance

cookslgln <- cooks.distance(lgln)
rlgln <- stdres(lgln)
a <- cbind(data4, cookslgln, rlgln)
a[cookslgln > 4/372, ]
# 46 observations have a larger than expected Cook's distance

cookslglg <- cooks.distance(lglg)
rlglg <- stdres(lglg)
a <- cbind(data4, cookslglg, rlglg)
a[cookslglg > 4/372, ]
# 22 observations have a larger than expected Cook's distance

# Look at absolute residuals:
rabs <- abs(r)
a <- cbind(data4, cooks, r, rabs)
asorted <- a[order(-rabs), ]
asorted[1:10, ]
# This has the highest absolute residuals

rabslgln <- abs(rlgln)
a <- cbind(data4, cookslgln, rlgln, rabslgln)
asorted <- a[order(-rabslgln), ]
asorted[1:10, ]
# This has the lowest absolute residuals

rabslglg <- abs(rlglg)
a <- cbind(data4, cookslglg, rlglg, rabslglg)
asorted <- a[order(-rabslglg), ]
asorted[1:10, ]
# These residuals are between the two other models

# Try running robus models

r_linear <- lmRob(avg_price ~ coral_cover + beach_width + rating + class + zip, data = data4)
summary(r_linear)
summary(linear)
# Coral negative in both, less negative in linear model

r_lgln <- lmRob(log(avg_price) ~ coral_cover + beach_width + rating + class + zip, data = data4)
summary(r_lgln)
summary(lgln)
# Robust model is less negative than normal model, p-value is also more significant

r_lglg <- lmRob(log(avg_price) ~ log(coral_cover) + log(beach_width + sqrt(1 + beach_width^2)) + log(rating) + log(class) + zip, data = data4)
summary(r_lglg)
summary(lglg)
# Normal model has more negative value for coral, but is less significant

# What happens if we remove outliers 101, 102, 104, 105, 170, 294, 297, 357?
data4$hotel_name[101]
data4$hotel_name[102]


data_clean <- data4 %>%
  filter(hotel_name != data4$hotel_name[101]) %>% 
  filter(hotel_name != data4$hotel_name[102]) %>% 
  filter(hotel_name != data4$hotel_name[104]) %>%
  filter(hotel_name != data4$hotel_name[105]) %>%
  filter(hotel_name != data4$hotel_name[170]) %>%
  filter(hotel_name != data4$hotel_name[294]) %>%
  filter(hotel_name != data4$hotel_name[297]) %>%
  filter(hotel_name != data4$hotel_name[357])

c_linear <- lm(avg_price ~ coral_cover + beach_width + rating + class + zip, data = data4)
summary(c_linear)
# Even without outliers, coral is still negative

```

```{r, results = "asis"}

# Models to show the team in SC
cities <- data4 %>% 
  group_by(city) %>% 
  summarize(
    mean_price = mean(avg_price),
    mean_coral = mean(coral_cover),
    mean_reefdist = mean(dist_to_reef),
    mean_rating = mean(rating),
    mean_class = mean(class),
    count = length(city)
  )
cities

# Regression models

simple <- lm(log(avg_price) ~ coral_cover + beach_width + rating + class + city, data = data4)
summary(simple)

simple_2 <- lm(log(avg_price) ~ coral_cover + beach_width + rating + class + dist_to_reef + dist_to_access_points, data = data4)
summary(simple_2)

simple_3 <- lm(log(avg_price) ~ coral_cover + beach_width + rating + class + dist_to_reef + dist_to_access_points + beachfront + pool + conference + concierge + gym + wifi + breakfast + air_trans + free_parking, data = data4)
summary(simple_3)

simple_city <- lm(log(avg_price) ~ coral_cover + beach_width + rating + class + dist_to_reef + dist_to_access_points + beachfront + pool + conference + concierge + gym + wifi + breakfast + air_trans + free_parking + city, data = data4)
summary(simple_city)

benefits_reg <- stargazer(simple, simple_3, simple_city, type = "html", report = "vc*", model.numbers = F, digits = 9, digits.extra = 1, 
                         title = "Ecotourism Log-Linear Regression Results",
                         dep.var.labels=c("Log of Standard Hotel Room Price"),
                         column.labels = c("Simple", "Model 2", "Model w/ City"),
                         covariate.labels = c("Coral Cover", "Beach Width", "Rating", "Class", "Distance to Reef", "Distance to Access Pts.", "Beachfront", "Pool", "Conference", "Concierge", "Gym", "Wifi", "Breakfast", "Air Transport", "Free Parking", "Key West", "Miami Beach"),
                         out = "benefits_reg.html")

# These same models by city

simple_fl <- lm(log(avg_price) ~ coral_cover + beach_width + rating + class + dist_to_reef + dist_to_access_points + beachfront + pool + conference + concierge + gym + wifi + breakfast + air_trans + free_parking, data = data_fl)
summary(simple_fl)

simple_kw <- lm(log(avg_price) ~ coral_cover + beach_width + rating + class + dist_to_reef + dist_to_access_points + beachfront + pool + conference + concierge + gym + wifi + breakfast + air_trans + free_parking, data = data_kw)
summary(simple_kw)

simple_mb <- lm(log(avg_price) ~ coral_cover + beach_width + rating + class + dist_to_reef + dist_to_access_points + beachfront + pool + conference + concierge + gym + wifi + breakfast + air_trans + free_parking, data = data_mb)
summary(simple_mb)

benefits_city <- stargazer(simple_fl, simple_kw, simple_mb, type = "html", report = "vc*", model.numbers = F, digits = 9, digits.extra = 1, 
                         title = "Ecotourism Log-Linear Regression Results by City",
                         dep.var.labels=c("Log of Standard Hotel Room Price"),
                         column.labels = c("Ft. Lauderdale", "Key West", "Miami Beach"),
                         covariate.labels = c("Coral Cover", "Beach Width", "Rating", "Class", "Distance to Reef", "Distance to Access Pts.", "Beachfront", "Pool", "Conference", "Concierge", "Gym", "Wifi", "Breakfast", "Air Transport", "Free Parking"),
                         out = "benefits_city.html")


```





































