---
title: "Final Paper Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

# Packages
library(tidyverse)
library(knitr)
library(readr)
#install.packages("stargazer")
library(stargazer)
#install.packages("janitor")
library(janitor)
library(MASS)
library(car)

```

```{r}

# Import and tidy data
data <- read_csv("regression_10km.csv")

# Reclassify columns
data$Pool <- as.factor(data$Pool)
data$Bar <- as.factor(data$Bar)
data$Biz_Center <- as.factor(data$Biz_Center)
data$Conference <- as.factor(data$Conference)
data$Mtg_Rooms <- as.factor(data$Mtg_Rooms)
data$Wheelchair <- as.factor(data$Wheelchair)
data$Concierge <- as.factor(data$Concierge)
data$Laundry <- as.factor(data$Laundry)
data$Gym <- as.factor(data$Gym)
data$Wifi <- as.factor(data$Wifi)
data$Multilingual <- as.factor(data$Multilingual)
data$No_Smoke <- as.factor(data$No_Smoke)
data$Breakfast_ <- as.factor(data$Breakfast_)
data$Air_Trans <- as.factor(data$Air_Trans)
data$Free_Parking <- as.factor(data$Free_Parking)
data$Beachfront <- as.factor(data$Beachfront)
data$City <- as.factor(data$City)
data$city_comp <- as.factor(data$city_comp)
data$dive_site <- as.factor(data$dive_site)
data$`3_star` <- as.factor(data$`3_star`)
data$`4_star` <- as.factor(data$`4_star`)
data$`5_star` <- as.factor(data$`5_star`)
data$near <- as.factor(data$near)
data$mid <- as.factor(data$mid)
data$far <- as.factor(data$far)
data$position <- as.factor(data$position)
data$zip <- as.factor(data$zip)

# Add a column with average price, select only wanted columns
data1 <- data %>%
  dplyr::select(2, 6:50, -LATITUDE, -LONGITUDE, -NEAR_DIST_SHORE) %>% 
  mutate(avg_price = (Low_Price + High_Price)/2) %>% 
  clean_names()
# Correct the rooms column to reviews
names(data1)[3] <- "num_reviews"
# n = 428 for data1

# Filter out hotels that are missing class and review data
data2 <- data1 %>% 
  filter(class != "#N/A" | number_rooms != "#N/A")
data2$class <- as.numeric(data2$class)
data2$number_rooms <- as.numeric(data2$number_rooms)
# n = 385 for data2

data4 <- data2 %>% 
  filter(city!= "Boca" & city != "Delray")
# n = 372 for data4

```

```{r results = "asis"}

# Create a df with summary of variables

data_summary <- data4 %>% 
  dplyr::select(avg_price, coral_cover, dist_to_reef, dive_site, beach_width, near_dist_beach, dist_to_access_points, class, rating, num_reviews, number_rooms, air_trans, bar, beachfront, biz_center, breakfast, concierge, conference, free_parking, gym, laundry, mtg_rooms, multilingual, no_smoke, wheelchair, wifi, dist_to_airport, city)

data_summary <- as.data.frame(data_summary)

#write.csv(data_summary, file = "data_summary.csv"

```

```{r}

# Regression models

simple <- lm(log(avg_price) ~ coral_cover + beach_width + rating + class + city, data = data4)
summary(simple)

simple_2 <- lm(log(avg_price) ~ coral_cover + beach_width + rating + class + dist_to_reef + dist_to_access_points, data = data4)
summary(simple_2)

simple_3 <- lm(log(avg_price) ~ coral_cover + beach_width + rating + class + dist_to_reef + dist_to_access_points + beachfront + pool + conference + concierge + gym + wifi + breakfast + air_trans + free_parking, data = data4)
summary(simple_3)

simple_city <- lm(log(avg_price) ~ coral_cover + beach_width + rating + class + dist_to_reef + dist_to_access_points + beachfront + pool + conference + concierge + gym + wifi + breakfast + air_trans + free_parking + city, data = data4)
summary(simple_city)

benefits_reg <- stargazer(simple, simple_3, simple_city, type = "html", report = "vc*", model.numbers = F, digits = 9, digits.extra = 1, 
                         title = "Ecotourism Log-Linear Regression Results",
                         dep.var.labels=c("Log of Standard Hotel Room Price"),
                         column.labels = c("Simple", "Model 2", "Model w/ City"),
                         covariate.labels = c("Coral Cover", "Beach Width", "Rating", "Class", "Distance to Reef", "Distance to Access Pts.", "Beachfront", "Pool", "Conference", "Concierge", "Gym", "Wifi", "Breakfast", "Air Transport", "Free Parking", "Key West", "Miami Beach"),
                         out = "benefits_reg.html")

# These same models by city

simple_fl <- lm(log(avg_price) ~ coral_cover + beach_width + rating + class + dist_to_reef + dist_to_access_points + beachfront + pool + conference + concierge + gym + wifi + breakfast + air_trans + free_parking, data = data_fl)
summary(simple_fl)

simple_kw <- lm(log(avg_price) ~ coral_cover + beach_width + rating + class + dist_to_reef + dist_to_access_points + beachfront + pool + conference + concierge + gym + wifi + breakfast + air_trans + free_parking, data = data_kw)
summary(simple_kw)

simple_mb <- lm(log(avg_price) ~ coral_cover + beach_width + rating + class + dist_to_reef + dist_to_access_points + beachfront + pool + conference + concierge + gym + wifi + breakfast + air_trans + free_parking, data = data_mb)
summary(simple_mb)

benefits_city <- stargazer(simple_fl, simple_kw, simple_mb, type = "html", report = "vc*", model.numbers = F, digits = 9, digits.extra = 1, 
                         title = "Ecotourism Log-Linear Regression Results by City",
                         dep.var.labels=c("Log of Standard Hotel Room Price"),
                         column.labels = c("Ft. Lauderdale", "Key West", "Miami Beach"),
                         covariate.labels = c("Coral Cover", "Beach Width", "Rating", "Class", "Distance to Reef", "Distance to Access Pts.", "Beachfront", "Pool", "Conference", "Concierge", "Gym", "Wifi", "Breakfast", "Air Transport", "Free Parking"),
                         out = "benefits_city.html")

```

```{r}

model <- lm(log(avg_price) ~ coral_cover + beach_width + class + rating, data = data4)
summary(model)

model1 <- lm(log(avg_price) ~ coral_cover + beach_width + class + rating + dist_to_reef, data = data4)
summary(model1)

model2 <- lm(log(avg_price) ~ coral_cover + beach_width + class + rating + dist_to_reef + dist_to_access_points, data = data4)
summary(model2)

model3 <- lm(log(avg_price) ~ coral_cover + beach_width + class + rating + dist_to_reef + dist_to_access_points + num_reviews, data = data4)
summary(model3)

model4 <- lm(log(avg_price) ~ coral_cover + beach_width + class + rating + dist_to_reef + dist_to_access_points + num_reviews + number_rooms, data = data4)
summary(model4)

model5 <- lm(log(avg_price) ~ coral_cover + beach_width + class + rating + dist_to_reef + dist_to_access_points + num_reviews + number_rooms + air_trans, data = data4)
summary(model5)

model6 <- lm(log(avg_price) ~ coral_cover + beach_width + class + rating + dist_to_reef + dist_to_access_points + num_reviews + number_rooms + air_trans + bar, data = data4)
summary(model6)

model7 <- lm(log(avg_price) ~ coral_cover + beach_width + class + rating + dist_to_reef + dist_to_access_points + num_reviews + number_rooms + air_trans + bar + beachfront, data = data4)
summary(model7)

model8 <- lm(log(avg_price) ~ coral_cover + beach_width + class + rating + dist_to_reef + dist_to_access_points + num_reviews + number_rooms + air_trans + bar + beachfront + biz_center, data = data4)
summary(model8)

model9 <- lm(log(avg_price) ~ coral_cover + beach_width + class + rating + dist_to_reef + dist_to_access_points + num_reviews + number_rooms + air_trans + bar + beachfront + biz_center + breakfast, data = data4)
summary(model9)

model10 <- lm(log(avg_price) ~ coral_cover + beach_width + class + rating + dist_to_reef + dist_to_access_points + num_reviews + number_rooms + air_trans + bar + beachfront + biz_center + breakfast + concierge, data = data4)
summary(model10)

model11 <- lm(log(avg_price) ~ coral_cover + beach_width + class + rating + dist_to_reef + dist_to_access_points + num_reviews + number_rooms + air_trans + bar + beachfront + biz_center + breakfast + concierge + conference, data = data4)
summary(model11)

model12 <- lm(log(avg_price) ~ coral_cover + beach_width + class + rating + dist_to_reef + dist_to_access_points + num_reviews + number_rooms + air_trans + bar + beachfront + biz_center + breakfast + concierge + conference + free_parking, data = data4)
summary(model12)

model13 <- lm(log(avg_price) ~ coral_cover + beach_width + class + rating + dist_to_reef + dist_to_access_points + num_reviews + number_rooms + air_trans + bar + beachfront + biz_center + breakfast + concierge + conference + free_parking + gym, data = data4)
summary(model13)

model14 <- lm(log(avg_price) ~ coral_cover + beach_width + class + rating + dist_to_reef + dist_to_access_points + num_reviews + number_rooms + air_trans + bar + beachfront + biz_center + breakfast + concierge + conference + free_parking + gym + laundry, data = data4)
summary(model14)

model15 <- lm(log(avg_price) ~ coral_cover + beach_width + class + rating + dist_to_reef + dist_to_access_points + num_reviews + number_rooms + air_trans + bar + beachfront + biz_center + breakfast + concierge + conference + free_parking + gym + laundry + mtg_rooms, data = data4)
summary(model15)

model16 <- lm(log(avg_price) ~ coral_cover + beach_width + class + rating + dist_to_reef + dist_to_access_points + num_reviews + number_rooms + air_trans + bar + beachfront + biz_center + breakfast + concierge + conference + free_parking + gym + laundry + mtg_rooms + multilingual, data = data4)
summary(model16)

model18 <- lm(log(avg_price) ~ coral_cover + beach_width + class + rating + dist_to_reef + dist_to_access_points + num_reviews + number_rooms + air_trans + bar + beachfront + biz_center + breakfast + concierge + conference + free_parking + gym + laundry + mtg_rooms + multilingual + no_smoke + wheelchair, data = data4)
summary(model18)

model19 <- lm(log(avg_price) ~ coral_cover + beach_width + class + rating + dist_to_reef + dist_to_access_points + num_reviews + number_rooms + air_trans + bar + beachfront + biz_center + breakfast + concierge + conference + free_parking + gym + laundry + mtg_rooms + multilingual + no_smoke + wheelchair + wifi, data = data4)
summary(model19)

model20 <- lm(log(avg_price) ~ coral_cover + beach_width + class + rating + dist_to_reef + dist_to_access_points + num_reviews + number_rooms + air_trans + bar + beachfront + biz_center + breakfast + concierge + conference + free_parking + gym + laundry + mtg_rooms + multilingual + no_smoke + wheelchair + wifi + dist_to_airport, data = data4)
summary(model20)

################################### Ones to include in report

model_1 <- lm(log(avg_price) ~ coral_cover + beach_width + class + rating, data = data4)
summary(model_1)
mean(vif(model_1))

model21 <- lm(log(avg_price) ~ coral_cover + beach_width + class + rating + dist_to_reef + dist_to_access_points, data = data4)
summary(model21)
mean(vif(model21))

model22 <- lm(log(avg_price) ~ coral_cover + beach_width + class + rating + dist_to_reef + dist_to_access_points + number_rooms + beachfront + conference, data = data4)
summary(model22)
vif(model22)
mean(vif(model22))

model23 <- lm(log(avg_price) ~ coral_cover + beach_width + class + rating + dist_to_reef + dist_to_access_points + number_rooms + beachfront + conference + city, data = data4)
summary(model23)

#lm(log(avg_price) ~ coral_cover + beach_width + rating + class + dist_to_reef + dist_to_access_points + beachfront + pool + conference + concierge + gym + wifi + breakfast + air_trans + free_parking

report <- stargazer(model_1, model21, model22, type = "html", model.numbers = F, digits = 9, title = "Ecotourism Log-Linear Aggregate Regression Results", dep.var.labels = c("Log of Standard Hotel Room Price"),
                    covariate.labels = c("Coral Cover", "Beach Width", "Hotel Class", "Guest Rating", "Distance to Reef", "Distance to Access", "# Rooms", "Beachfront", "Conference Center"),
                    column.labels = c("1", "2", "3", "4"),
                    out = "report.html")

############################################### City models

model22_city <- lm(log(avg_price) ~ coral_cover + beach_width + class + rating + dist_to_reef + dist_to_access_points + number_rooms + beachfront + conference + city, data = data4)
summary(model22_city)
mean(vif(model22_city))
vif(model22_city)

data_mb <- data4 %>% 
  filter(city == "MiamiBeach")

data_kw <- data4 %>% 
  filter(city == "KeyWest")

data_fl <- data4 %>% 
  filter(city == "FtLauderdale")

model22_fl <- lm(log(avg_price) ~ coral_cover + beach_width + class + rating + dist_to_reef + dist_to_access_points + number_rooms + beachfront + conference, data = data_fl)
summary(model22_fl)
mean(vif(model22_fl))
vif(model22_fl)

model22_kw <- lm(log(avg_price) ~ coral_cover + beach_width + class + rating + dist_to_reef + dist_to_access_points + number_rooms + beachfront + conference, data = data_kw)
summary(model22_kw)
mean(vif(model22_kw))
vif(model22_kw)

model22_mb <- lm(log(avg_price) ~ coral_cover + beach_width + class + rating + dist_to_reef + dist_to_access_points + number_rooms + beachfront + conference, data = data_mb)
summary(model22_mb)
mean(vif(model22_mb))
vif(model22_mb)

report_city <- stargazer(model22_city, model22_fl, model22_kw, model22_mb, type = "html", model.numbers = F, digits = 9, title = "Ecotourism Log-Linear Local Regression Results", dep.var.labels = c("Log of Standard Hotel Room Price"),
                    covariate.labels = c("Coral Cover", "Beach Width", "Hotel Class", "Guest Rating", "Distance to Reef", "Distance to Access", "# Rooms", "Beachfront", "Conference Center", "Key West", "Miami Beach"),
                    column.labels = c("3 + City", "Fort Lauderdale", "Key West", "Miami Beach"),
                    out = "report_city.html")

#######################################################

#compare <- stargazer(model, model1, model2, model3, model4, model5, model6, model7, model8, model9, model10, model11, model12, model13, model14, model15, model16, model17, model18, model19, model20, type = "html", report = "vc*", model.numbers = F, digits = 9, 
                        # title = "Ecotourism Log-Linear Regression Results by City",
                        # dep.var.labels=c("Log of Standard Hotel Room Price"),
                        # column.labels = c("Model", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"),
                        # out = "compare.html")

all <- lm(log(avg_price) ~ coral_cover + beach_width + class + rating + dist_to_reef + beach_width + dist_to_access_points + dive_site + num_reviews + number_rooms + air_trans + bar + beachfront + biz_center + breakfast + concierge + conference + free_parking + gym + laundry + mtg_rooms + multilingual + no_smoke + wheelchair + wifi + dist_to_airport, data = data4)
summary(all)

all_city <- lm(log(avg_price) ~ coral_cover + beach_width + class + rating + dist_to_reef + dive_site + beach_width + near_dist_beach + dist_to_access_points + num_reviews + number_rooms + air_trans + bar + beachfront + biz_center + breakfast + concierge + conference + free_parking + gym + laundry + mtg_rooms + multilingual + no_smoke + wheelchair + wifi + dist_to_airport + city, data = data4)
summary(all_city)



```

```{r}

# Create new columns that put coral cover into km^2 and distance to airport into km
data5 <- data4 %>% 
  mutate(coral_km2 = coral_cover/1000000) %>% 
  mutate(airport_km = dist_to_airport/1000)

# Summarize with new metrics
cities <- data5 %>% 
  group_by(city) %>% 
  summarize(
    mean_price = mean(avg_price),
    sd_price = sd(avg_price),
    min_price = min(avg_price),
    max_price = max(avg_price),
    mean_coral = mean(coral_km2),
    sd_coral = sd(coral_km2),
    min_coral = min(coral_km2),
    max_coral = max(coral_km2),
    mean_beach = mean(beach_width),
    sd_beach = sd(beach_width),
    min_beach = min(beach_width),
    max_beach = max(beach_width),
    mean_rooms = mean(number_rooms),
    sd_rooms = sd(number_rooms),
    min_rooms = min(number_rooms),
    max_rooms = max(number_rooms),
    count = length(city)
  )
cities

# Re-run pooled models with adjusted metrics

model_1 <- lm(log(avg_price) ~ coral_km2 + beach_width + class + rating, data = data5)
summary(model_1)
mean(vif(model_1))

model21 <- lm(log(avg_price) ~ coral_km2 + beach_width + class + rating + dist_to_reef + dist_to_access_points, data = data5)
summary(model21)
mean(vif(model21))

model22 <- lm(log(avg_price) ~ coral_km2 + beach_width + class + rating + dist_to_reef + dist_to_access_points + number_rooms + beachfront + conference, data = data5)
summary(model22)
vif(model22)
mean(vif(model22))

report <- stargazer(model_1, model21, model22, 
                    type = "html", 
                    model.numbers = F, 
                    digits = 4, 
                    title = "Ecotourism Log-Linear Pooled Regression Results",  
                    omit.stat = c("rsq"), 
                    dep.var.labels = c("Log of Standard Hotel Room Price"),
                    covariate.labels = c("<p>Coral Cover (km<sup>2</sup>)</p>", "Beach Width (m)", "Hotel Class", "Guest Rating", "Distance to Reef (m)", "Distance to Access (m)", "# Rooms", "Beachfront", "Conference Center"),
                    column.labels = c("1", "2", "3"),
                    out = "report_km2.html")

# Re-run city and local models with adjusted metrics

model22_city <- lm(log(avg_price) ~ coral_km2 + beach_width + class + rating + dist_to_reef + dist_to_access_points + number_rooms + beachfront + conference + city, data = data5)
summary(model22_city)
mean(vif(model22_city))
vif(model22_city)

data_mb <- data5 %>% 
  filter(city == "MiamiBeach")

data_kw <- data5 %>% 
  filter(city == "KeyWest")

data_fl <- data5 %>% 
  filter(city == "FtLauderdale")

model22_fl <- lm(log(avg_price) ~ coral_km2 + beach_width + class + rating + dist_to_reef + dist_to_access_points + number_rooms + beachfront + conference, data = data_fl)
summary(model22_fl)
mean(vif(model22_fl))
vif(model22_fl)

model22_kw <- lm(log(avg_price) ~ coral_km2 + beach_width + class + rating + dist_to_reef + dist_to_access_points + number_rooms + beachfront + conference, data = data_kw)
summary(model22_kw)
mean(vif(model22_kw))
vif(model22_kw)

model22_mb <- lm(log(avg_price) ~ coral_km2 + beach_width + class + rating + dist_to_reef + dist_to_access_points + number_rooms + beachfront + conference, data = data_mb)
summary(model22_mb)
mean(vif(model22_mb))
vif(model22_mb)

report_city <- stargazer(model22_city, model22_fl, model22_kw, model22_mb, 
                         type = "html", 
                         model.numbers = F, 
                         digits = 4, 
                         title = "Ecotourism Log-Linear Local Regression Results",
                         dep.var.labels = c("Log of Standard Hotel Room Price"), 
                         omit.stat = c("rsq"),
                         covariate.labels = c("<p>Coral Cover (km<sup>2</sup>)</p>", "Beach Width (m)", "Hotel Class", "Guest Rating", "Distance to Reef (m)", "Distance to Access (m)", "# Rooms", "Beachfront", "Conference Center", "Key West", "Miami Beach"),
                         column.labels = c("3 + City", "Fort Lauderdale", "Key West", "Miami Beach"),
                         out = "report_city_km2.html")

  

```













