---
title: "NI_Sand Stabilization Regression"
output:
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r tools, echo = F, message = F, include = F}

library(tidyverse)
library(knitr)
library(readr)
#install.packages("stargazer")
library(stargazer)
install.packages("janitor")
library(janitor)
library(MASS)

```

Our Research Questions:
1. Does beach width significantly impact hotel revenue?
2. Does ecotourism significantly impact hotel revenue as measured by amount of coral and distance to popular dive sites?

```{r echo = F, message = F, include = F}

# Import data
data <- read_csv("regression_20km_new.csv")
#View(data)

# Correct data classes
data$Pool <- as.factor(data$Pool)
data$Bar <- as.factor(data$Bar)
data$Biz_Center <- as.factor(data$Biz_Center)
data$Conference <- as.factor(data$Conference)
data$Mtg_Rooms <- as.factor(data$Mtg_Rooms)
data$Wifi <- as.factor(data$Wifi)
data$Multilingual <- as.factor(data$Multilingual)
data$No_Smoke <- as.factor(data$No_Smoke)
data$Breakfast_ <- as.factor(data$Breakfast_)
data$Air_Trans <- as.factor(data$Air_Trans)
data$Free_Parking <- as.factor(data$Free_Parking)
data$Beachfront <- as.factor(data$Beachfront)
data$Wheelchair <- as.factor(data$Wheelchair)
data$Concierge <- as.factor(data$Concierge)
data$Laundry <- as.factor(data$Laundry)
data$Gym <- as.factor(data$Gym)
data$City <- as.factor(data$City)
data$dive_site <- as.factor(data$dive_site)
data$near_shore <- as.factor(data$near_shore)
data$mid_shore <- as.factor(data$mid_shore)
data$far_shore <- as.factor(data$far_shore)
data$`3_star` <- as.factor(data$`3_star`)
data$`4_star` <- as.factor(data$`4_star`)
data$`5_star` <- as.factor(data$`5_star`)

# Add a column with average price
data1 <- data %>%
  dplyr::select(2, 4:44, -LATITUDE, -LONGITUDE) %>% 
  mutate(avg_price = (Low_Price + High_Price)/2) %>% 
  clean_names()

# Correct the rooms column to reviews
names(data1)[5] <- "num_reviews"

```

```{r results = "asis"}

# Filter out Key West
data_nokw <- data1 %>% 
  filter(city != "KeyWest")
#View(data_nokw)

# Filter out Boca
data_noboca <- data1 %>% 
  filter(city != "Boca")
#View(data_noboca)

```

```{r}

# Linear regression for coral simple:

coral_lm <- lm(avg_price ~ coral_cover + rating + near_dist_beach, data = data1)
summary(coral_lm)

coral_lglg <- lm(log(avg_price) ~ log(coral_cover) + log(rating) + log(near_dist_beach) + log(beach_width + sqrt(1 + beach_width^2)) + near_shore, data = data1)
summary(coral_lglg)

coral_lglg <- lm(log(avg_price) ~ log(coral_cover) + log(rating) + log(near_dist_beach), data = data1)
summary(coral_lglg)

coralbeach_lm <- lm(avg_price ~ coral_cover + beach_width + rating + near_dist_beach, data = data1)
summary(coralbeach_lm)

# Try adding cities
coral_city_lm <- lm(avg_price ~ coral_cover + rating + near_dist_beach + city, data = data1)
summary(coral_city_lm)

coralbeach_city_lm <- lm(avg_price ~ coral_cover + beach_width + rating + near_dist_beach, data = data1)
summary(coralbeach_city_lm)

coral_city_lm_low <- lm(low_price ~ coral_cover + rating + near_dist_beach + city, data = data1)
summary(coral_city_lm_low)

coralbeach_city_lm_low <- lm(low_price ~ coral_cover + beach_width + rating + near_dist_beach, data = data1)
summary(coralbeach_city_lm_low)

```

```{r}

# Try a stepwise regression
all_lm <- lm(avg_price ~ coral_cover + beach_width + rating + num_reviews + pool + bar + biz_center + conference + mtg_rooms + wheelchair + concierge + laundry + gym + wifi + multilingual + no_smoke + breakfast + air_trans + free_parking + beachfront + near_dist_beach + beach_width + dist_to_access_points + dist_to_airport + dist_to_dive + dist_to_reef + num_dive + dive_site, data = data1)

step <- stepAIC(all_lm, direction = "both")
step$anova

# Model recommended by stepwise regression: avg_price ~ coral_cover + rating + pool + conference + mtg_rooms + air_trans + beachfront + dive_site

step <- lm(avg_price ~ coral_cover + rating + pool + conference + mtg_rooms + air_trans + beachfront + dive_site, data = data1)
summary(step)

beach_lm <- lm(avg_price ~ beach_width + rating + pool + conference + mtg_rooms + air_trans + beachfront)

idea <- lm(avg_price ~ coral_cover + rating + pool + conference + air_trans + beachfront + dive_site + dist_to_reef + dist_to_access_points, data = data1)
summary(idea)

city_lm <- lm(avg_price ~ coral_cover + rating + pool + conference + air_trans + mtg_rooms + beachfront + dist_to_reef + dist_to_access_points + city, data = data1)
summary(city_lm)

city_nob_lm <- lm(avg_price ~ coral_cover + rating + pool + conference + air_trans + beachfront + dist_to_reef + dist_to_access_points + city, data = data_noboca)
summary(city_nob_lm)

stripes_lm <- lm(avg_price ~ coral_cover + rating + pool + conference + air_trans + beachfront + dive_site + dist_to_reef + dist_to_access_points + near_shore + mid_shore, data = data1)
summary(stripes_lm)

compare <- stargazer(step, idea, city_lm, city_nob_lm, stripes_lm, type = "html",
                         title = "Linear Models - 20km Distance",
                         column.labels = c("Step Analysis", "Our Anlaysis", "With Cities", "W/O Boca", "With Shore Zones (200m)"),
                         out = "compare20km.html")

all_lm_lglg <- lm(log(avg_price) ~ log(coral_cover) + log(beach_width + sqrt(1 + beach_width^2)) + log(rating) + log(num_reviews) + pool + bar + biz_center + conference + mtg_rooms + wheelchair + concierge + laundry + gym + wifi + multilingual + no_smoke + breakfast + air_trans + free_parking + beachfront + log(near_dist_beach) + log(dist_to_access_points) + log(dist_to_airport) + log(dist_to_dive) + log(dist_to_reef) + log(num_dive + sqrt(1 + num_dive^2)) + dive_site, data = data1)

step_lglg <- stepAIC(all_lm_lglg, direction = "both")
step_lglg$anova

# Model recommended by stepwise log log regression: log(avg_price) ~ log(coral_cover) + log(beach_width + sqrt(1 + beach_width^2)) + log(rating) + log(num_reviews) + pool +     conference + mtg_rooms + concierge + gym + multilingual + breakfast + air_trans + beachfront

test_lglg <- lm(log(avg_price) ~ log(coral_cover) + log(beach_width + sqrt(1 + beach_width^2)) + log(rating) + log(num_reviews) + pool + conference + concierge + gym + multilingual + air_trans + beachfront, data = data1)
summary(test_lglg)

data_nob <- data1 %>% 
  filter(city != "Boca")

all_lm_nob <- lm(avg_price ~ coral_cover + beach_width + rating + num_reviews + pool + bar + biz_center + conference + mtg_rooms + wheelchair + concierge + laundry + gym + wifi + multilingual + no_smoke + breakfast + air_trans + free_parking + beachfront + near_dist_beach + beach_width + dist_to_access_points + dist_to_airport + dist_to_dive + dist_to_reef + num_dive + dive_site, data = data_nob)

step_nob <- stepAIC(all_lm, direction = "both")
step_nob$anova

test_nob <- lm(avg_price ~ coral_cover + rating + pool + conference + mtg_rooms + air_trans + beachfront + dive_site, data = data_nob)
summary(test_nob)

width <- lm(beach_width ~ coral_cover + dist_to_reef + city, data = data1)
summary(width)

width_nob <- lm(beach_width ~ coral_cover + dist_to_reef, data = data_nob)
summary(width_nob)

data_nok <- data1 %>% 
  filter(city != "KeyWest")

width_nok <- lm(beach_width ~ coral_cover + dist_to_reef, data = data_nok)
summary(width_nok)


```

```{r}
# Another stepwise regression:
all_lm <- lm(avg_price ~ coral_cover + beach_width + rating + num_reviews + pool + bar + biz_center + conference + mtg_rooms + wheelchair + concierge + laundry + gym + wifi + multilingual + no_smoke + breakfast + air_trans + free_parking + beachfront + near_dist_beach + dist_to_access_points + dist_to_airport + dist_to_dive + dist_to_reef + num_dive + dive_site + num_dive + city + near_shore + mid_shore, data = data1)

all_lm_low <- lm(low_price ~ coral_cover + beach_width + rating + num_reviews + pool + bar + biz_center + conference + mtg_rooms + wheelchair + concierge + laundry + gym + wifi + multilingual + no_smoke + breakfast + air_trans + free_parking + beachfront + near_dist_beach + beach_width + dist_to_access_points + dist_to_airport + dist_to_dive + dist_to_reef + num_dive + dive_site + num_dive + city + near_shore + mid_shore, data = data1)

all_step <- stepAIC(all_lm, direction = "both")
all_step$anova

all_lm_low <- stepAIC(all_lm_low, direction = "both")
all_lm_low$anova

lm_low <- lm(low_price ~ coral_cover + rating + num_reviews + pool + mtg_rooms + concierge + gym + breakfast + air_trans + beachfront + dist_to_airport + dist_to_dive + city, data = data1)
summary(lm_low)

lm_low_nob <- lm(avg_price ~ coral_cover + rating + num_reviews + pool + mtg_rooms + concierge + gym + breakfast + air_trans + beachfront + dist_to_airport + dist_to_dive + city, data = data1)
summary(lm_low_nob)

example <- stargazer(lm_low_nob, type = "html",
                         title = "Linear Models - 20km Distance",
                         column.labels = c("Step no Boca"),
                         out = "compare20km.html")

```

```{r}

# Log log step models:

log_all <- lm(log(avg_price) ~ log(coral_cover) + log(beach_width + sqrt(1 + beach_width^2)) + log(rating) + log(num_reviews) + pool + bar + biz_center + conference + mtg_rooms + wheelchair + concierge + laundry + gym + wifi + multilingual + no_smoke + breakfast + air_trans + free_parking + beachfront + log(near_dist_beach) + log(dist_to_access_points) + log(dist_to_airport) + log(dist_to_reef) + log(num_dive + sqrt(1 + num_dive^2)) + near_shore + mid_shore, data = data1)
summary(log_all)

log_all_step <- stepAIC(log_all, direction = "both")
log_all_step$anova

log_model <- lm(log(low_price) ~ log(coral_cover) + log(beach_width + sqrt(1 + beach_width^2)) + log(rating) + log(num_reviews) + pool + conference + mtg_rooms + concierge + gym + multilingual + breakfast + air_trans + beachfront + city, data = data1)

example <- stargazer(log_model, type = "html",
                         title = "Log Model - 20 km",
                         column.labels = c("Log Model"),
                         out = "example20km.html")
names(data1)

data_miami <- data1 %>% 
  filter(city == "MiamiBeach")

log_miami <- lm(log(avg_price) ~ log(coral_cover) + log(beach_width + sqrt(1 + beach_width^2)) + log(rating) + log(num_reviews) + pool + bar + biz_center + conference + mtg_rooms + wheelchair + concierge + laundry + gym + wifi + multilingual + no_smoke + breakfast + air_trans + free_parking + beachfront + log(near_dist_beach) + log(dist_to_access_points) + log(dist_to_airport) + log(dist_to_reef) + dive_site + near_shore + mid_shore, data = data1)
summary(log_miami)
resid(log_miami)

plot(resid(log_miami))

```

```{r}

new_lm <- lm(avg_price ~ coral_cover + class + number_rooms + rating + num_reviews + pool + bar + biz_center + conference + mtg_rooms + wheelchair + concierge + laundry + gym + wifi + multilingual + no_smoke + breakfast + air_trans + free_parking + beachfront + near_dist_beach + near_dist_shore + beach_width + dist_to_access_points + dist_to_airport + dist_to_dive + dist_to_reef + num_dive + city + dive_site + near_shore + mid_shore, data = data3)

new_step <- stepAIC(new_lm, direction = "both")
new_step$anova

try_lm <- lm(avg_price ~ class + number_rooms + rating + num_reviews + conference + air_trans + beachfront + beach_width + dist_to_dive, data = data4)
summary(try_lm)

try_coral <- lm(avg_price ~ coral_cover + class + number_rooms + rating + num_reviews + conference + air_trans + beachfront + dist_to_reef + city, data = data4)
summary(try_coral)

coral <- stargazer(try_lm, try_coral, type = "html",
                         title = "Linear Models - 20km Distance",
                         column.labels = c("Step LM", "Coral LM"),
                         out = "coral20km.html")

data4 <- data3 %>% 
  filter(city != "Boca")

coral_pt <- ggplot(data4, aes(x = coral_cover, y = avg_price )) +
  geom_point()
coral_pt

reef_box <- ggplot(data4, aes(x = city, y = coral_cover)) +
  geom_boxplot()
reef_box

beach_lm <- lm(avg_price ~ beach_width + dist_to_reef + class + rating + city, data = data4)
summary(beach_lm)


```

```{r}
# Try some log log regressions with the new data

log_new <- lm(log(avg_price) ~ log(coral_cover) + x3_star + x4_star + x5_star + log(number_rooms) + log(num_reviews) + pool + bar + biz_center + conference + mtg_rooms + wheelchair + concierge + laundry + gym + wifi + multilingual + no_smoke + breakfast + air_trans + free_parking + beachfront + log(near_dist_beach) + log(dist_to_access_points) + log(dist_to_airport) + log(dist_to_reef) + log(num_dive + sqrt(1 + num_dive^2)) + city, data = data1)

log_new_nob <- lm(log(avg_price) ~ log(coral_cover) + x3_star + x4_star + x5_star + log(number_rooms) + log(num_reviews) + pool + bar + biz_center + conference + mtg_rooms + wheelchair + concierge + laundry + gym + wifi + multilingual + no_smoke + breakfast + air_trans + free_parking + beachfront + log(near_dist_beach) + log(dist_to_access_points) + log(dist_to_airport) + log(dist_to_reef) + city, data = data_noboca)

log_coral <- stargazer(log_new, log_new_nob, type = "html",
                         title = "Log Models - 20km Distance",
                         column.labels = c("All Cities", "W/o Boca"),
                         out = "coral20km.html")

log_step <- stepAIC(log_new, direction = "both")
log_step$anova

model_try <- lm(log(avg_price) ~ log(coral_cover) + x3_star + x4_star + x5_star + log(number_rooms) + pool + biz_center + conference + wheelchair + concierge + log(near_dist_beach) + log(dist_to_access_points) +  log(dist_to_airport) + log(num_dive + sqrt(1 + num_dive^2)) + city, data = data1)
summary(model_try)

reef_box <- ggplot(data1, aes(x = city, y = coral_cover)) +
  geom_boxplot()
reef_box

price_box <- ggplot(data1, aes(x = city, y = avg_price)) +
  geom_boxplot()
price_box

price_coral <- ggplot(data1, aes(x = coral_cover, y = avg_price)) +
  geom_point(aes(color = city) )
price_coral

stats <- data1 %>% 
  group_by(city) %>% 
  summarize(
    mean_price = mean(avg_price, na.rm = T, sort = desc),
    mean_coral = mean(coral_cover, na.rm = T),
    mean_class = mean(class),
    mean_rating = mean(rating),
    count = length(city)
  )

stats

```













